name: CI/CD React App

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   build_and_test:
      runs-on: ubuntu-latest
   permissions:
      contents: write # Autoriser l'action à modifier le contenu du dépôt (pousser vers gh-pages)
      pages: write # Autoriser l'action à déployer sur GitHub Pages

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install dependencies
           run: npm install

         - name: Run tests
           run: npm run test

         - name: Build project
           run: npm run build

         - name: Deploy to GitHub Pages
           if: success()
           uses: JamesIves/github-pages-deploy-action@v4
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: gh-pages
              folder: build
